name: ApigeeLint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  apigeelint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your Apigee project
        uses: actions/checkout@v4

      - name: Set up Node.js 20 (required for apigeelint >=2.74.0)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clone ApigeeLint
        run: |
          git clone https://github.com/apigee/apigeelint.git
          cd apigeelint
          npm ci || npm install
          npm link

      - name: Verify ApigeeLint installation
        run: npm list -g --depth=0 | grep apigeelint || true

      - name: Run ApigeeLint (table format)
        run: |
          echo "Running ApigeeLint in table format..."
          apigeelint -s ./apiproxy -f table || true

      - name: Run ApigeeLint (JSON) and save report
        run: |
          echo "Running ApigeeLint JSON scan..."
          apigeelint -s ./apiproxy -f json > apigeelint-report.json || true

      - name: Print JSON report (for preview)
        run: |
          echo "===== ApigeeLint JSON Report Preview ====="
          cat apigeelint-report.json

      - name: Check for error severity and fail if found
        run: |
          echo "Checking for severity: error..."
          if grep -q '"severity":"error"' apigeelint-report.json; then
            echo "❌ Security issues found. Rejecting PR."
            exit 1
          else
            echo "✅ No critical security issues found. Proceeding PR successfully."
          fi

      - name: Upload lint report (always run)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apigeelint-report
          path: apigeelint-report.json
